### ISSUE TITLE
Only one channel

### ISSUE THREAD

**Issue by Johnsonzcode** [DataCenter-of-ICMM/MOMS#1]
Hi @relipmoc 

Is it possible to use this tool with only one channel ?

Johnson
Best

**Comment by relipmoc** [comment]
Dear Johnson,
   Thank you for your question! Unfortunately, this tool is designed for scaffolding with multiple channels. If you have optical maps with only one channel, I suggest you use the official scaffolder provided by BioNano Genomics.
   All the best
   Hongshan

**Comment by Johnsonzcode** [comment]
Thank you for your reply!
